# Nom de l'application
spring.application.name=rendezvous

# Configuration de la base de données (valeurs par défaut si non fournies)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/rendezvous?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# Configuration du serveur
server.port=${SERVER_PORT:8081}
server.servlet.context-path=/Rendezvous

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
